import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/src/components/Layout/Header/Header";
import Footer from "@/src/components/Layout/Footer/Footer";
import Banner from "@/src/components/SingleProjectComponents/Banner/Banner";
import ProjectMap from "@/src/components/SingleProjectComponents/ProjectMap/ProjectMap";
import Properties from "@/src/components/SingleProjectComponents/Properties/Properties";
import ProjectList from "@/src/components/SingleProjectComponents/ProjectList/ProjectList";
import Units from "@/src/components/SingleProjectComponents/Units/Units";
import Developer from "@/src/components/SingleProjectComponents/Developer/Developer";

export default function SingleProjectPage({
  project,
  properties,
  projectList,
  units,
}) {
  return (
    <>
      <Head>
        <title>Single Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.page}>
          <Header />
          <Banner data={project} />
          <Developer data={project} />
          <Units data={units} />
          <ProjectMap data={project} />
          <ProjectList data={projectList} />
          <Properties data={projectList} />
          <Footer />
        </div>
      </main>
    </>
  );
}

// export async function getStaticPaths() {
//   return {
//     paths: [],
//     fallback: "blocking", // false or 'blocking'
//   };
// }

export const getServerSideProps = async (context) => {
  const { id } = context.query;
  // const { query } = context?.req || {};
  // const { id } = query || {};
  // console.log("id", id);
  // const response = await fetch(
  //   `https://aqar.api.mvp-apps.ae/api/mob_app/public/project/getProjectById/${id}`
  // );
  // const data = await response.json();

  try {
    // Fetch the project data by ID
    const response = await fetch(
      `https://aqar.api.mvp-apps.ae/api/mob_app/public/project/getProjectById/${id}`
    );

    if (!response.ok) {
      // If the response is not successful, redirect to the "Page Not Found"
      return {
        redirect: {
          destination: "/not-found", // Replace with the path to your custom 404 page
          permanent: false,
        },
      };
    }

    const data = await response.json();

    if (!data.data) {
      // If the project data is empty or undefined
      return {
        redirect: {
          destination: "/not-found", // Replace with the path to your custom 404 page
          permanent: false,
        },
      };
    }

    // /////////////////////

    const response2 = await fetch(
      "https://aqar.api.mvp-apps.ae/api/mob_app/public/property/getPropertyList"
    );
    const data2 = await response2.json();
    const response3 = await fetch(
      "https://aqar.api.mvp-apps.ae/api/mob_app/public/project/getProjectList?page=1&limit=10"
    );
    const data3 = await response3.json();
    const response4 = await fetch(
      "https://aqar.api.mvp-apps.ae/api/mob_app/public/project/projectProperty/getProjectPropertyListforPublic?project_id=35"
    );
    const data4 = await response4.json();
    return {
      props: {
        project: data.data,
        properties: data2.data,
        projectList: data3.data,
        units: data4.data,
      },
    };
  } catch (error) {
    // Redirect to the "Page Not Found" in case of any error
    console.error(error);
    return {
      redirect: {
        destination: "/not-found", // Replace with the path to your custom 404 page
        permanent: false,
      },
    };
  }
};
